# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wo1zaf2erATUfSjcHKubs8sl6XdueRxn
"""

!pip install pytorch-lightning

from PIL import Image
import os
import numpy as np
import torch
import matplotlib.pyplot as plt
import seaborn as sns
import urllib.request
from torch.utils.tensorboard import SummaryWriter
import pandas as pd
from torch import nn
from torch.nn import functional as F
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from torchvision.datasets import LFWPairs
from torchvision import transforms
import torchvision
from imageio.core.util import OrderedDict
from torch.optim import lr_scheduler
import time
import urllib
from torchvision.datasets import ImageFolder
from torchvision.transforms import transforms
from tqdm import tqdm
from torchvision.transforms import ToTensor, Grayscale
import torch.nn as nn
import torch.optim as optim
import pytorch_lightning as pl
from torchvision.transforms import Grayscale, Resize, ToTensor, Compose
from torchvision.transforms.functional import to_pil_image
import torch.nn.init as init
from torch.optim.lr_scheduler import ExponentialLR
from torchmetrics.classification import Accuracy
import torch.nn.functional as F

data_directory = '/content/drive/MyDrive/lfw2'
image_paths = []
labels = []

# Iterate over subdirectories in the main data directory
for person_dir in os.listdir(data_directory):
    person_path = os.path.join(data_directory, person_dir)
    # Check if the item in the main directory is a subdirectory
    if os.path.isdir(person_path):
        # Iterate over files and directories in the subdirectory
        for item_name in os.listdir(person_path):
            item_path = os.path.join(person_path, item_name)
            # Check if the item is a file and ends with '.jpg'
            if os.path.isfile(item_path) and item_name.endswith('.jpg'):
                # Append the full path of the image file and the label to the lists
                image_paths.append(item_path)
                labels.append(person_dir)

train_file_url = "https://vis-www.cs.umass.edu/lfw/pairsDevTrain.txt"
test_file_url = "https://vis-www.cs.umass.edu/lfw/pairsDevTest.txt"

urllib.request.urlretrieve(train_file_url, 'pairsDevTrain.txt')
urllib.request.urlretrieve(test_file_url, 'pairsDevTest.txt')
def read_pairs_file(file_path):
    pairs = []
    with open(file_path, 'r') as file:
        for line in file:
            pairs.append(line.strip().split('\t'))
    return pairs

train_pairs = read_pairs_file('pairsDevTrain.txt')[1:]
test_pairs = read_pairs_file('pairsDevTest.txt')[1:]
print("Train pairs:")
print(train_pairs[1102])
print("Test pairs:")
print(test_pairs[1])

class ImagePairDataset(Dataset):
    def __init__(self, data_directory, pairs_file, transform=None):
        self.data_directory = data_directory
        self.pairs_file = pairs_file
        self.image_pairs, self.labels = self.extract_image_pairs()
        self.transform = transform

    def extract_image_pairs(self):
        image_pairs = []
        labels = []  # To store the labels
        with open(self.pairs_file, 'r') as file:
            for line in file:
                pair_info = line.strip().split('\t')
                if len(pair_info) == 3:
                    name, num1, num2 = pair_info
                    label = 1
                    image1 = self.load_image(name, num1)
                    image2 = self.load_image(name, num2)
                    image_pairs.append((image1, image2))
                    labels.append(label)
                elif len(pair_info) == 4:
                    name1, num1, name2, num2 = pair_info
                    label = 0
                    image1 = self.load_image(name1, num1)
                    image2 = self.load_image(name2, num2)
                    image_pairs.append((image1, image2))
                    labels.append(label)
        return image_pairs, labels

    def __len__(self):
        return len(self.image_pairs)

    def __getitem__(self, idx):
        image1, image2 = self.image_pairs[idx]
        label = self.labels[idx]

        # Apply transformations if provided
        if self.transform:
            image1 = self.transform(image1)
            image2 = self.transform(image2)

        return image1, image2, label

    def load_image(self, name, num):
        image_path = os.path.join(self.data_directory, name, f"{name}_{num.zfill(4)}.jpg")
        image = Image.open(image_path)
        return image

transform = transforms.Compose([
            transforms.Resize((105, 105)),
            transforms.Grayscale(),
            transforms.ToTensor(),
            transforms.RandomAffine(degrees=(-10, 10), translate=(0.1, 0.1), scale=(0.8, 1.2), shear=(-0.3, 0.3)),
        ])

data_directory = '/content/drive/MyDrive/lfw2/lfw2'
train_pairs_file = '/content/pairsDevTest.txt'
test_pairs_file = '/content/pairsDevTrain.txt'
batch_size = 128

train_dataset = ImagePairDataset(data_directory, train_pairs_file, transform=transform)
test_dataset = ImagePairDataset(data_directory, test_pairs_file, transform=transform)
train_data, val_data = train_test_split(train_dataset, test_size=0.1, random_state=42)

train_loader = DataLoader(train_data, batch_size=batch_size, shuffle=True,num_workers=2)
val_loader = DataLoader(val_data, batch_size=batch_size, shuffle=False,num_workers=2)  # No need to shuffle validation data
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False,num_workers=2)  # No need to shuffle test data

class SiameseNetwork(nn.Module):
    def __init__(self, input_shape):
        super(SiameseNetwork, self).__init__()
        self.cnn = nn.Sequential(
            nn.Conv2d(input_shape[0], 64, kernel_size=10),
            nn.BatchNorm2d(64),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=2, stride=2),
            nn.Conv2d(64, 128, kernel_size=7),
            nn.BatchNorm2d(128),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=2, stride=2),
            nn.Conv2d(128, 128, kernel_size=4),
            nn.BatchNorm2d(128),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=2, stride=2),
            nn.Conv2d(128, 256, kernel_size=4),
            nn.BatchNorm2d(256),
            nn.ReLU(inplace=True)
        )

        # initialize the weights according to the specifications in the paper - later in the class we define _initialize_weights function
        self._initialize_weights()

        # determine the size of the output feature tensor after passing through the CNN with the help of  _get_conv_output that we define later in the class
        n_size = self._get_conv_output(input_shape)

        # Fully connected layer to produce embeddings
        self.fc = nn.Sequential(
            nn.Linear(n_size, 4096),
            nn.BatchNorm1d(4096)
        )

         # Learnable parameters for weighting the component-wise distance
        self.alpha =nn.Sequential(
            nn.Linear(4096,1)
        )


    def _initialize_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.normal_(m.weight, mean=0, std=1e-2)
                nn.init.normal_(m.bias, mean=0.5, std=1e-2)
            elif isinstance(m, nn.Linear):
                nn.init.normal_(m.weight, mean=0, std=2e-1)
                nn.init.normal_(m.bias, mean=0.5, std=1e-2)

    def _get_conv_output(self, shape):
        bs = 1
        input = torch.autograd.Variable(torch.rand(bs, *shape))
        output_feat = self.cnn(input)
        n_size = output_feat.data.view(bs, -1).size(1)
        return n_size

    def forward_one(self, x):
        x = self.cnn(x)
        x = torch.flatten(x, start_dim=1)
        x = self.fc(x)
        return x

    def forward(self, input_a, input_b):
        output_a = self.forward_one(input_a)
        output_b = self.forward_one(input_b)
        abs_diff = torch.abs(output_a - output_b)
        similarity_score = self.alpha(abs_diff)

        return similarity_score

class SiameseLightning(pl.LightningModule):

    def __init__(self, input_shape, learning_rate=1e-3):
        '''
        This method initializes the SiameseLightning model with a specified input shape and learning rate.
        input:
            input_shape (tuple): The shape of the input images.
            learning_rate (float): The learning rate for training the model by defualt-->1e-3.
        This method sets up the Siamese Network model, specifies the loss function as Binary Cross-Entropy with Logits (which does not assume a sigmoid activation in the final layer), and sets the learning rate for the optimizer.
        '''

        super(SiameseLightning, self).__init__()
        self.model = SiameseNetwork(input_shape)
        self.loss_fn = nn.BCEWithLogitsLoss() #assumes the model's final layer doesn't include a sigmoid activation
        self.learning_rate = learning_rate


    def forward(self, input_a, input_b):
        '''
        This method returns the output of the SiameseNetwork
        '''
        return self.model(input_a, input_b)


    def calculate_accuracy(self, similarity_scores, labels, threshold=0.5):
      '''
      This method calculates accuracy after each training and validation step
      to monitor how well the model is learning
      '''
      # apply sigmoid to convert similarity scores to probabilities
      probabilities = torch.sigmoid(similarity_scores)

      # convert probabilities to binary predictions based on the threshold
      predictions = (probabilities >= threshold).float()

      # calculate the number of correct predictions
      correct_predictions = (predictions == labels.float()).float().sum()

      # calculate the accuracy
      accuracy = correct_predictions / labels.size(0)

      return accuracy


    def training_step(self, batch, batch_idx):
        input_a, input_b, labels = batch
        labels=labels.long()
        labels = labels.float()
        similarity_scores = self(input_a, input_b).squeeze()
        loss = self.loss_fn(similarity_scores, labels)
        accuracy = self.calculate_accuracy(similarity_scores, labels)
        self.log('train_loss', loss, on_epoch=True, prog_bar=True)
        self.log('train_accuracy', accuracy, on_epoch=True, prog_bar=True)
        print('train_loss', loss,'train_accuracy', accuracy)
        return loss

    def validation_step(self, batch, batch_idx):
        input_a, input_b, labels = batch
        labels=labels.long()
        labels = labels.float()  # Ensure labels are of type float for BCEWithLogitsLoss
        similarity_scores = self(input_a, input_b).squeeze()  # Ensure similarity scores are squeezed to 1D tensor if necessary
        val_loss = self.loss_fn(similarity_scores, labels)
        val_accuracy = self.calculate_accuracy(similarity_scores, labels)
        self.log('val_loss', val_loss, on_epoch=True, prog_bar=True)
        self.log('val_accuracy', val_accuracy, on_epoch=True, prog_bar=True)
        print('val_loss', val_loss,'val_accuracy', val_accuracy)
        return val_loss

    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.model.parameters(), lr=self.learning_rate)
        scheduler = torch.optim.lr_scheduler.ExponentialLR(optimizer, gamma=0.99)
        return {'optimizer': optimizer, 'lr_scheduler': scheduler}

# Initialize your SiameseLightning model
model = SiameseLightning(input_shape=(1,105,105))

# Define a trainer
trainer = pl.Trainer(max_epochs=100)

# Train the model
trainer.fit(model, train_loader, val_loader)

# Test the model
trainer.test(test_loader)